### ISSUE TITLE
How to add any messages or log to specific test case in allure reporting ?

### ISSUE THREAD

**Issue by kkashyap1707** [allure-framework/allure-jasmine#19]
Hi Team
@d0lfin @just-boris 

I wants to add some custom steps into a test case using Allure Reporting.
![test step](https://cloud.githubusercontent.com/assets/4715140/22825815/3ae6e5b6-efb5-11e6-8d87-1878823b86d8.png)

As of now in the above screenshot , you can find only two steps is displayed. I wants to append more test steps for more clarification. How can i implement it.

Please find the attached conf.js
[Conf file.txt](https://github.com/allure-framework/allure-jasmine/files/766569/Conf.file.txt)
 file for reference.

Thanks 
Keshav

**Comment by matt-mccrudden1** [comment]
+1
@just-boris

**Comment by just-boris** [comment]
The test execution log contains all steps calls. Steps should be defined via `allure.createStep` method.


```
const myStep = allure.createStep('myStep', () => {
 // do something
})
```

Whenever you call `myStep()` in your test code, the call will appear in respective testcase in the report.

**Comment by matt-mccrudden1** [comment]
Thanks @just-boris , unfortunately I'm not able to get this working 

Where do I define const myStep? Conf or spec?  Where exactly do I call myStep();
For the // do something, I'm using page object model - do I put a POM 'function' like 'Get Url' in here?

In my spec files, I require page-objects and then build jasmine It blocks by calling reusable functions created in those POM files. I'm not sure sure where I fit create step into this.

Ideally I'd like the report to just list each POM function that was called and run in the spec. For example,

Homepage.GetUrl
Homepage.ClickButton

Thanks in advance for the help! 👍

**Comment by just-boris** [comment]
You can follow Mocha example: https://github.com/allure-examples/mocha-allure-example
We have no good example for Jasmine (you can contribute this to us!), but Mocha API is very similar, so code samples are petty much same.

You can place `allure.createStep` calls everywhere. Maybe you will have to do [this workaround](https://github.com/allure-examples/mocha-allure-example/blob/master/test/simple.spec.js#L9) if it doesn't work without.
