### ISSUE TITLE
Error : Cannot find name 'allure' in typescript, any missing dependencies?

### ISSUE THREAD

**Issue by shivanthalakmal** [allure-framework/allure-jasmine#21]
![image](https://cloud.githubusercontent.com/assets/7554175/24190245/17626ade-0f0e-11e7-8fcd-e76fb8638682.png)

Used dependencies :

  "dependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "@types/jasmine": "^2.5.38",
    "protractor": "^5.1.1",
    "typescript": "^2.2.1",
    "typescript-logging": "^0.2.0",
    "typescript-map": "0.0.3"
  },
  "devDependencies": {
    "jasmine-allure-reporter": "^1.0.1",
    "jasmine-console-reporter": "^1.2.7",
    "jasmine-data_driven_tests": "^1.0.0",
    "protractor-helpers": "^1.1.0",
    "protractor-jasmine2-html-reporter": "0.0.7",
    "ts-json-properties": "^1.1.4"
  },

Could you help me? what is it wrong in my typescript code ?

**Comment by just-boris** [comment]
`allure` is a global identifier, injected by reporter to your code.

Add the following line to the top of your file to tell Typescript about it

```ts
declare const allure: any;
```

**Comment by shivanthalakmal** [comment]
Thank you very much @just-boris it re-solved my issue
