### ISSUE TITLE
allure report is not generated in results directory when test fail in protractor using jasmine framework

### ISSUE THREAD

**Issue by saisagar-vuddagiri** [allure-framework/allure-jasmine#24]
Hi guys,

allure report is not generated in results directory when test fails in protractor using jasmine framework.

Below is the stake trace:

  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by
jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)

Version deatils are below.
========================
jasmine-version:2.4.1

on prepare function: 
========================
onPrepare: function(){        
	
		!fs.existsSync(__dirname + '/allure-results') &&  fs.mkdirSync(__dirname + '/allure-results');
		var reporterPath = path.resolve(path.join(__dirname, '/allure-results'));
		
		var reporter = new AllureReporter({
        allureReport : {
				resultsDir : '/allure-results'
			}
		});
		jasmine.getEnv().addReporter(reporter);
		jasmine.getEnv().afterEach(function(done){
			browser.takeScreenshot().then(function (png) {
				allure.createAttachment('Screenshot', function () {
					return new Buffer(png, 'base64')
				}, 'image/png')();
				done();
			})
		});
	    },

Please help me out. Thanks in adavance.

Best Regards,
Sagar

**Comment by shivanthalakmal** [comment]
Stack:
Error: Timeout - Async callback was not invoked within timeout specified by
jasmine.DEFAULT_TIMEOUT_INTERVAL.

according to my understand this error occur when what ever page load time get too much time, and seems this error not relate with allure report, any way just try this code,

      var AllureReporter = require('jasmine-allure-reporter');
      var reporter = new AllureReporter({
          allureReport : {
              resultsDir : 'allure-results'
          }
      });
      jasmine.getEnv().addReporter(reporter);
      jasmine.getEnv().afterEach(function(){
          browser.takeScreenshot().then(function (png) {
              allure.createAttachment('Screenshot', function () {
                  return new Buffer(png, 'base64')
              }, 'image/png')();
          })
      });

**Comment by saisagar-vuddagiri** [comment]
Thanks for the reply @shivanthalakmal.

I tried with your code. Sometimes the report is getting generated successfully and sometimes not. I am not sure about the reason for that. There is no error displaying in cmd. 

Anyways its working fine, can you please help me on how to capture the exceptions during run time. Is try/catch block suffices or we need to handle it  in the promise?

**Comment by premkh9** [comment]
Even I am observing similar issues, in case of failures, report is not getting generated. 
It would be really great if you can help us to fix this issue

**Success Results**
[16:08:08] I/testLogger -

[16:08:08] I/launcher - 0 instance(s) of WebDriver still running
[16:08:08] I/launcher - chromelatest #01-1 passed
[16:08:08] I/launcher - chromelatest #01-0 passed

> choice-hotels-js@5.2.2 posttest C:\Users\pkashipa\git\choice-hotels-js
> allure generate allure-results --clean -o allure-report || true

Report successfully generated to allure-report

**Failure Results** 
[16:14:49] I/testLogger -

[16:14:49] I/launcher - 0 instance(s) of WebDriver still running
[16:14:49] I/launcher - chromelatest #01-1 passed
[16:14:49] I/launcher - chromelatest #01-0 failed 1 test(s)
[16:14:49] I/launcher - overall: 1 failed spec(s)
[16:14:49] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.

**Comment by just-boris** [comment]
Ensure that you run `allure generate` regardless of the exit code of the last command.

For example, you can split them in your job configuration

```sh
npm test # runs tests
test_exit_code=$? # save exit code for later
allure generate # generate allure results
exit "$test_exit_code" # exit with the right exit code to fail the build
```

**Comment by premkh9** [comment]
Hi Just, Thanks for your help... I used below config and its working in success and failures

"scripts": {
  "pretest": "echo pretest",
  "test": "mocha || :",
  "posttest": "echo posttest"
}

**Comment by just-boris** [comment]
Ok, so we will keep this as a general recommendation for that case. Closing the issue.

**Comment by sravankumarreddybade** [comment]
Can you help me on how to do this in my test
Ensure that you run allure generate regardless of the exit code of the last command.
For example, you can split them in your job configuration
npm test # runs tests
test_exit_code=$? # save exit code for later
allure generate # generate allure report
exit "$test_exit_code" # exit with the right exit code to fail the build
