### ISSUE TITLE
Issue: Adding Snapshot to the Test Case Level using Jasmine and TypeScript with Allure reporter

### ISSUE THREAD

**Issue by anuvratashu** [allure-framework/allure-jasmine#25]
I am getting the error while using allure reporter with jasmine and typescript.
```
jasmine.getEnv().afterEach(done => {
            browser.takeScreenshot().then(function (png) {              
                allure.createAttachment('Screenshot', function () {
                    return new Buffer(png, 'base64')
                }, 'image/png')();
        done();
            });
        });
```

Here as typescript check the type , so i am getting the below error for the line
However, the same code works fine with Javascript and jasmine.

So please help how to have the same code work for typescript and jasmine
jasmine.getEnv().afterEach(done => 

**[ts] Argument of type '(done: any) => void' is not assignable to parameter of type '() => void'.
(parameter) done: any'**

**Comment by just-boris** [comment]
You are correct. The Jasmine typings that come from [there](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts#L172) do not have a signature with callback.

However, there is nothing to do with Allure in particular, so I will close the issue.

Please file an issue in the appropriate projects, e.g. Jasmine repo or its [typing definition](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasmine)
