### ISSUE TITLE
Description type is being ignored in the report.

### ISSUE THREAD

**Issue by karthi79** [allure-framework/allure-jasmine#28]
I am using description type to log description with some html in it but the html tags being escaped while generating the report. 

`allure.description("line 1\r\n line 2","markdown") `
or
` allure.description("line 1 <br/> line 2","html")`

In the report, it's displaying <br/> as it is and expecting line break in the report.

it looks like type attribute not getting added to description tag in xml file. see below sample, there is no type attribute generated for the description.

`<description>line 1 &lt; br &gt; </description>`

**Comment by just-boris** [comment]
As of 2.0 Allure supports only descriptions in Markdown. Type passed via the second argument is not taken anymore.

**Comment by karthi79** [comment]
Thanks, can you provide sample syntax for markdown in description?

**Comment by karthi79** [comment]
Thanks. Can you provide sample description in markdown? I am trying to create a bullet list in markdown but below code outputs * instead of bullet point and in the second one text is not bold. See markdown syntax is also not working for me. I'm using jasmine-allure-reporter 1.0.1 version.

```
allure.description('* Step1  ' +
      '* Step2  ');
```
Or
```
allure.description('**1. Step1**  ' +
      '**2.Step2**  ');
```

**Comment by just-boris** [comment]
Regarding marked lists, there is already existing issue: https://github.com/allure-framework/allure2/issues/582

Second code snippet worked well for me, it produced bold text as I expected.

**Comment by karthi79** [comment]
but for me, this is how the output looks like in the report for 2nd one.
![image](https://user-images.githubusercontent.com/16444881/32183733-51fc0d1a-bd57-11e7-89f7-fa06ccb7bfe0.png)

**Comment by just-boris** [comment]
You use older allure-commandline, version 1.x. Please upgrade to 2.x

**Comment by karthi79** [comment]
I'm using Gradle to generate the report. Is there a new version for Gradle too?

**Comment by just-boris** [comment]
This is definitely not a good place to ask such question. But it seems like https://github.com/allure-framework/allure-gradle already has 2.4 release

**Comment by karthi79** [comment]
@just-boris, It worked after upgrading to 2.4. Thanks.
