### ISSUE TITLE
Steps executed in beforeAll fails all the case

### ISSUE THREAD

**Issue by cakeinpanic** [allure-framework/allure-jasmine#30]
We have some pageObject with Steps, which are helping us to test our allpication

Sometimes we run some steps in beforeAll to prepare application for the suite
In this case allure fails the test with message
`TypeError: Cannot read property 'addStep' of undefined`

**Comment by just-boris** [comment]
If I understand you correctly, you have the following code

```js
describe("a spec", () => {
  const stepFn = () => {};
  const step = allure.createStep("test step", stepFn);

  beforeAll(() => {
    step(); // <- this doesn't work
    console.log("before all");
  });
  it("is a test", () => {
    step(); // <- this works well
    console.log("tested");
  });
});
```

Why not call just `stepFn` instead of `step` in the `beforeAll` section? Anyway, this step will never be recorded.

**Comment by cakeinpanic** [comment]
yes, it is my case
but using your solution is problematic because we have huge pageobjects full of reusable steps(including nested ones), and storing methods twice looks impossible

this code represents our tests structure
```
const openUseProfile = = allure.createStep("open profile", ()=>{});

const openAuthForm = allure.createStep("open form", ()=>{});
const clickOnLoginButton = = allure.createStep("click on btn", ()=>{});
const inputLoginData = = allure.createStep("input data", ()=>{});
const login = allure.createStep("login into app", ()=>{
    openAuthForm();
    inputLoginData();
    clickOnLoginButton();
});

// this whole suite fails
describe("profile test", () => {
  beforeAll(() => {
    login(); 
  });
  it("we can open profile", () => {
    openUserProfile();
    console.log("tested");
  });
});

// this suite works great
describe("login test", () => {
  it("login form works correctly", () => {
    inputLoginData();
  });
});
```

**Comment by irushah** [comment]
+1

**Comment by cakeinpanic** [comment]
Fixed within https://github.com/allure-framework/allure-js-commons/pull/30
