### ISSUE TITLE
pom.xml removed 

### ISSUE THREAD

**Issue by jgegger** [allure-framework/allure-jasmine#33]
The documentation references the ready-to-use pom.xml file. The file was removed as part of cbd72529ec95781e2f6f97c05a77c6e31dde6381.

Regards,
Jonathan

**Comment by jitmatz** [comment]
How to generate allure report after this change?

**Comment by just-boris** [comment]
```
npm install allure-commandline --save-dev
```

Then add a `posttest` section into your `package.json`

```
"scripts": {
  "posttest": "allure generate allure-results --clean -o allure-report"
}
```

`npm test` will run this command after the test itself ends.

Please, send a PR with documentation change. I am running out of time and can't do this myself. For the time being, use Mocha example: https://github.com/allure-examples/mocha-allure-example/blob/master/package.json

**Comment by jitmatz** [comment]
@just-boris ,
I added 'posttest' in my package.json file as you said. But no data is showing in the report. It showing '404 - not found'.

**Comment by jitmatz** [comment]
@just-boris , Thanks. It is working. 

But found one issue. It showing `404 - Not found` message in the report. It is working fine in latest firefox version - 57.0(64-bit)

**Comment by just-boris** [comment]
@jitmatz https://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome

**Comment by just-boris** [comment]
Instruction has been updated.
