### ISSUE TITLE
pom.xml deleted - request to update doc, how to use maven

### ISSUE THREAD

**Issue by zwingliernst** [allure-framework/allure-jasmine#40]
With this commit here, the ready-to-use pom.xml got deleted.
https://github.com/allure-framework/allure-jasmine/commit/2639e23d723e97890971f9e076806758886a2c7b

Also here there is already asked of in SO with two very different type of answers. However, it's not clear, what is supported or works better.
https://stackoverflow.com/questions/47512468/cannot-find-pom-xml-file-inside-allure-reporter-folder

Can you please update the readme.md to instruct, how the Maven setup now should work?
Thank you in advance

**Comment by just-boris** [comment]
Use allure-commandline. There is a section in readme: https://github.com/allure-framework/allure-jasmine#using-allure-command-line-tool
