### ISSUE TITLE
POM.xml is not found in jasmine-allure-reporter folder.

### ISSUE THREAD

**Issue by SwathiJayabharathi** [allure-framework/allure-jasmine#45]
i have done the following steps.
1. installed jasmine-allure-reporter.
2. Downloaded Maven and added the path to Environment variables.
3. Executed the testcases.
4. Reports are generated and while converting that to HTML, i have used following command.
mvn site -Dallure.results_pattern=allure-results

Following message is displayed.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.124 s
[INFO] Finished at: 2018-09-06T13:09:56+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\swathi_j\Workspace\WIP\VSWorkspace\node_modules\jasmine-allure-reporter). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Please help me to resolve this

**Comment by baev** [comment]
No need to use Maven. Follow the steps described in documentation https://github.com/allure-framework/allure-jasmine#using-allure-command-line-tool
