### ISSUE TITLE
Do we have typescript support for this library?

### ISSUE THREAD

**Issue by sriramkishoren** [allure-framework/allure-jasmine#48]
Do we have typescript support for this library? 
I am looking for something like this: npm install @types/jasmine-allure-reporter
I want to use this in my typescript project

**Comment by baev** [comment]
Our team working on new versions of JavaScript integrations witten on typescript (see allure-js repository)

At the moment new allure jasmine reporter is available here https://www.npmjs.com/package/jasmine-allure2-reporter

**Comment by sseliverstov** [comment]
@sriramkishoren finally repo is https://github.com/allure-framework/allure-js and written in typescript
