### ISSUE TITLE
Is there a functionality to display the Average Time taken for a test to Run in TimeLine Tab

### ISSUE THREAD

**Issue by anuvratashu** [allure-framework/allure-jasmine#6]
In the Time Line tab , it displays the time taken to run the test. However there is a label called Default displayed. So what does that mean in  a report . 

Also is there any way of displaying the Average 
![timeline tab](https://cloud.githubusercontent.com/assets/14295329/13249039/e3541c02-da47-11e5-8f23-6f8199fa3888.png)
time taken to run the test as a time bar???

**Comment by just-boris** [comment]
This labels usually shows the actual hostname, where tests were run. Allure intended to show reports about multi-threaded parallel tests, even if they run on different workers. I think that is a good point to hide it if `default` is the only visible option.

**Comment by just-boris** [comment]
Show average is a good thing, but I am not sure, that we can show it on the timeline.

We considered to show some more statistics at xUnit tab, but there is no place to show extra column next to `Duration`.
![screen shot 2016-02-23 at 14 02 05](https://cloud.githubusercontent.com/assets/812240/13249558/0e5970bc-da36-11e5-94e1-c92b893c1828.png)

But anyway, I take your request and try to do something with it.

**Comment by anuvratashu** [comment]
Thanks! for taking up the request. Please update once this is completed:)

**Comment by ctapobep** [comment]
I hardly can come up with a use case when average values is of any use. Usually we only need the slowest tests. @anuvratashu how are you going to use this statistics?

**Comment by anuvratashu** [comment]
if we are saving the data in the database and wanted to know the average time taken for a month long data and it can be generated in the allure report somehow.

**Comment by anuvratashu** [comment]
any update??

**Comment by just-boris** [comment]
@anuvratashu I don't think that there will be updates in short time.

We put this in our plans, we are going to make redesign, see https://github.com/allure-framework/allure-core/issues/721

Then we can do somethig with your request. 

Also your issue in the allure-core itself, not the jasmine only. So, you should create issue in core repo and close this one then. (Sorry, but Github doesn't have handy migration tool for that, only copy-paste)

**Comment by ctapobep** [comment]
I personally didn't hear answer to my question - I understand that some why the reporter needs average. But I don't get why and how this information is going to be used. I doubt that this feature is really useful - it'll take more space on the screen than it'll provide benefits.

**Comment by just-boris** [comment]
Outdated. 
Please, create a new issue in [Allure v2](https://github.com/allure-framework/allure2) repository, if the request is still actual.
