### ISSUE TITLE
Only the first “expect” failure for a testcase is logged in the report

### ISSUE THREAD

**Issue by Jayasankar-m** [allure-framework/allure-jasmine#7]
I'm using protractor with jasmine-allure reporter. In a test, when multiple "expect" statements are there,only the first "expect" statement result gets logged in the allure report.

The test continues even if an "expect" statement fails.But only the error for the first "expect" is logged in allure report.

I need all the failures for all the expect statements in the testcase to be displayed in the allure report. 
Is there any way i can achieve this?

Thanks!!

**Comment by valburyakov** [comment]
I faced the same problem while using jasmine-allure reporter. It's a bit confusing when you have a lot of failures in tests. 
<img width="1632" alt="one_expect_failure_in_report" src="https://cloud.githubusercontent.com/assets/18645670/17358154/1987ca4e-5969-11e6-9d87-3ea89037c8d6.png">

And I'm looking forward for solving this ussue.

**Comment by just-boris** [comment]
Hello!

Unfortunately, but now this is crucial restriction from Allure Core. Test can have only one falure object. We assuming that if first assertion failed, the rest of test means nothing because something went wrong.

It might be possible to change it in future, but it requires major change in Core project, so it will not be very soon.

**Comment by valburyakov** [comment]
I made some temp solution for this purpose, if tests have more than 1 failures then we create attach with this list. 
@just-boris What do you think it is correct to use in this way ? For me it works. Mb is there some problem with this in future ? 
```javascript
jasmine.getEnv().addReporter(new function() {
      this.specDone = function(result) {
        if (result.failedExpectations.length > 1) {
          var list = result.failedExpectations
              .reduce(function (acc, expectation) {return acc + expectation.message + '\n'; }, '');
          
          allure.createAttachment('Failed Expectations', function () {return list}, 'text/plain')();
        }
      };
    });
```

**Comment by just-boris** [comment]
If it is important for you to see all possible errors, you can do that.

But the thing is this is not a failure in terms of Allure. That means that Defects tab, for example, will ignore that data.
